import { Hash, Layers3, Search, Users } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { FollowingCollection, UnifiedSource, WorkspaceState } from "../types";
import { useBrowsingScope } from "../hooks/useBrowsingScope"; import { useUnifiedTimeline } from "../hooks/useUnifiedTimeline"; import { getUnifiedFollowing } from "../services/unified"; import { collectionPosts } from "../services/unified/aggregate"; import { PostCard } from "./unified/PostCard"; import { SourceControls } from "./unified/SourceControls"; import { ViewHeader } from "./unified/ViewHeader";
const typeLabel = { PERSON: "People", TOPIC: "Topics & tags", FEED: "Lists / feeds" } as const;
function makeCollections(sources: readonly UnifiedSource[]): FollowingCollection[] { return [{ id: "all", title: "All Following", description: "Posts from people, topics, and feeds you follow across selected accounts.", sources }, ...(["PERSON", "TOPIC", "FEED"] as const).map(type => ({ id: type.toLowerCase(), title: typeLabel[type], description: `All followed ${typeLabel[type].toLowerCase()} across selected accounts.`, sources: sources.filter(source => source.type === type) }))]; }
export function FollowingView({ workspace }: { workspace: WorkspaceState }) { const scope = useBrowsingScope("following", workspace.accounts); const accounts = useMemo(() => workspace.accounts.filter(account => scope.selected.includes(account.id)), [workspace.accounts, scope.selected]); const feed = useUnifiedTimeline(accounts); const [sources, setSources] = useState<UnifiedSource[]>([]); const [selectedId, setSelectedId] = useState("all"); const [query, setQuery] = useState("");
  useEffect(() => { const controller = new AbortController(); void getUnifiedFollowing(accounts, controller.signal).then(setSources); return () => controller.abort(); }, [accounts]); const collections = makeCollections(sources); const selected = collections.find(collection => collection.id === selectedId) ?? collections[0]; const posts = collectionPosts(selected, feed.posts).filter(post => post.text.toLowerCase().includes(query.toLowerCase()));
  return <div className="unified-page"><ViewHeader icon={<Users />} title="Following" subtitle="People, topics, and feeds from every network — in one place." controls={<SourceControls accounts={workspace.accounts} selected={scope.selected} onToggle={scope.toggle} onSelectProvider={scope.selectProvider} />} /><div className="following-layout"><aside className="collection-column panel"><h2>Collections</h2>{collections.map(collection => <button key={collection.id} className={selected.id === collection.id ? "selected" : ""} onClick={() => setSelectedId(collection.id)}>{collection.id === "person" ? <Users /> : collection.id === "topic" ? <Hash /> : <Layers3 />}<span><strong>{collection.title}</strong><small>{collection.sources.length} sources</small></span></button>)}{sources.length === 0 && <p className="aside-copy">Followed sources are not exposed by the selected accounts or instances.</p>}</aside><section className="feed-column"><div className="collection-heading panel"><Layers3 /><div><h2>{selected.title}</h2><p>{selected.description}</p></div></div><div className="search-row"><label><Search size={17} /><span className="sr-only">Search following posts</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search this collection…" /></label></div>{feed.loading && !feed.posts.length ? <div className="post-skeletons"><i /><i /></div> : posts.map(post => <PostCard post={post} accounts={workspace.accounts} key={post.canonicalKey} />)}{!feed.loading && !posts.length && <div className="panel empty-state"><Layers3 /><h3>No posts in this collection</h3><p>This collection has no returned posts in the currently loaded home feeds.</p></div>}</section><aside className="details-column"><section className="panel sticky-detail"><h2>Source details</h2><div className="detail-topic">{selected.title}</div><p className="aside-copy">{selected.description}</p><div className="source-detail-list">{selected.sources.map(source => <div key={source.id}><span className="mini-avatar">{source.type === "TOPIC" ? "#" : source.title[0]}</span><span><strong>{source.title}</strong><small>{typeLabel[source.type]} · {workspace.accounts.find(account => account.id === source.accountId)?.handle}</small></span></div>)}</div></section></aside></div></div>;
}
