import { Filter, Home, Search } from "lucide-react";
import { useMemo, useState } from "react";
import type { WorkspaceState } from "../types";
import { useBrowsingScope } from "../hooks/useBrowsingScope";
import { useUnifiedTimeline } from "../hooks/useUnifiedTimeline";
import { filterPosts } from "../services/unified/aggregate";
import { FailureStrip } from "./unified/FailureStrip"; import { PostCard } from "./unified/PostCard"; import { SourceControls } from "./unified/SourceControls"; import { ViewHeader } from "./unified/ViewHeader";
export function TimelineView({ workspace }: { workspace: WorkspaceState }) {
  const scope = useBrowsingScope("timeline", workspace.accounts); const selectedAccounts = useMemo(() => workspace.accounts.filter(account => scope.selected.includes(account.id)), [workspace.accounts, scope.selected]); const feed = useUnifiedTimeline(selectedAccounts); const [query, setQuery] = useState("");
  const posts = filterPosts(feed.posts, scope.selected).filter(post => `${post.author.displayName} ${post.author.handle} ${post.text}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="unified-page"><ViewHeader icon={<Home />} title="Timeline" subtitle="One chronological stream across every selected account." controls={<SourceControls accounts={workspace.accounts} selected={scope.selected} onToggle={scope.toggle} onSelectProvider={scope.selectProvider} />} /><div className="unified-layout"><section className="feed-column"><div className="search-row"><label><Search size={17} /><span className="sr-only">Search timeline</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search loaded posts, people, or topics…" /></label><button className="button"><Filter size={16} />Latest first</button></div><FailureStrip failures={feed.failures} accounts={workspace.accounts} retry={feed.retry} />{feed.loading && !feed.posts.length ? <div className="post-skeletons" aria-label="Loading timeline"><i /><i /><i /></div> : posts.map(post => <PostCard key={post.canonicalKey} post={post} accounts={workspace.accounts} />)}{!feed.loading && !posts.length && <div className="panel empty-state"><Home /><h3>No posts in this scope</h3><p>Select another account, retry a disconnected source, or wait for new posts.</p></div>}{feed.hasMore && <button className="button load-more" disabled={feed.loading} onClick={() => void feed.more()}>{feed.loading ? "Loading…" : "Load more"}</button>}</section><aside className="details-column"><section className="panel"><h2><Filter size={17} /> Reading scope</h2><p className="aside-copy">Timeline combines provider home feeds, removes duplicate remote IDs, and keeps every account attribution.</p>{workspace.accounts.map(account => <label className="scope-account" key={account.id}><input type="checkbox" checked={scope.selected.includes(account.id)} onChange={() => scope.toggle(account.id)} /><span>{account.displayName}<small>{account.handle}</small></span></label>)}</section></aside></div></div>;
}
